[package]
name = "book-api"
version = "0.1.0"
authors = ["Sudaraka Wijesinghe <sudaraka@sudaraka.org>"]

[dependencies]
diesel = { version = "^1.0", features = [ "mysql" ] }
dotenv = "^0.11"
r2d2 = "^0.8"
r2d2-diesel = "^1.0"
rocket = "^0.3"
